name: Examine
on:
  push:
  workflow_dispatch:
jobs:
  examine:
    runs-on: ubuntu-latest
    steps:
      # - uses: shaowenchen/debugger-action@v2
      #   name: debugger
      #   timeout-minutes: 30
      #   continue-on-error: true
      #   with:
      #     frp_server_addr: ${{ secrets.FRP_SERVER_ADDR }}
      #     frp_server_port: ${{ secrets.FRP_SERVER_PORT }}
      #     frp_token: ${{ secrets.FRP_TOKEN }}
      #     ssh_port: ${{ secrets.SSH_PORT }}
      - name: Checkout source
        uses: actions/checkout@v2
      - name: examine
      #   run: |
      #     systemctl status sshd
      #     sudo apt install expect
      #     chmod +x ./change_password.sh
      #     ./change_password.sh
      # - name: sudoers check
      #   run: |
      #     sudo cat /etc/sudoers
      # - name: install expect
      #   run: |
      #     sudo apt install expect
      # - name: passwd
      #   run: |
      #     chmod +x ./runner_instance_test/change_password.sh
      #     ./runner_instance_test/change_password.sh
      # - name: permit root ssh
      #   run: |
      #     chmod +x ./runner_instance_test/permit_root_ssh.sh
      #     ./runner_instance_test/permit_root_ssh.sh
      # - name: ssh to self
      #   run: |
      #     chmod +x ./runner_instance_test/ssh_to_self.sh
      #     ./runner_instance_test/ssh_to_self.sh
      - name: install n2n
        run: |
          sudo apt install alien
          sudo alien --scripts ./runner_instance_test/n2n-3.0.0-1038.x86_64.rpm
          sudo dpkg -i ./runner_instance_test/n2n-3.0.0-1038.x86_64.deb
          sudo ls /etc
          sudo ls /etc/n2n
      # - name: check arch (x86_64)
      #   run: |
      #     arch

