name: Examine
on:
  workflow_dispatch:
jobs:
  examine:
    runs-on: ubuntu-latest
    steps:
      # - uses: shaowenchen/debugger-action@v2
      #   name: debugger
      #   timeout-minutes: 30
      #   continue-on-error: true
      #   with:
      #     frp_server_addr: ${{ secrets.FRP_SERVER_ADDR }}
      #     frp_server_port: ${{ secrets.FRP_SERVER_PORT }}
      #     frp_token: ${{ secrets.FRP_TOKEN }}
      #     ssh_port: ${{ secrets.SSH_PORT }}
      - name: Checkout source
        uses: actions/checkout@v2
      - name: examine
        run: |
          systemctl status sshd
          sudo apt install expect
          chmod +x ./ssh_login.sh
          ./ssh_login.sh
