name: Realtime
on:
  push:
  workflow_dispatch:
jobs:
  realtime:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with: 
        python-version: "3.10"
    - name: Realtime test
      run: |
        python ./realtime/realtime.py
    - name: Another realtime test
      run: |
        python ./realtime/realtime.py
    - name: Another realtime test again
      run: |
        python ./realtime/realtime.py
