name: Test variables
on:
  workflow_dispatch:
jobs:
  test_variables:
    runs-on: ubuntu-latest
    steps:
      - name: Generate variable
        run: |
          echo VERSION1="HOORAY1" >> "$GITHUB_ENV"
          echo VERSION2="HOORAY2" >> "$GITHUB_ENV"
          echo VERSION3="HOORAY3" >> "$GITHUB_ENV"
      - name: Show variables
        run: |
          echo ${{ env.VERSION1 }}