name: Test variables
on:
  workflow_dispatch:
jobs:
  test_variables:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v4
      - name: Generate variable
        id: generate_variable
        run: |
          export ME=$(whoami)
          echo "{me}={$ME}" >> $GITHUB_OUTPUT
      - name: Show variables 1
        run: |
          echo ${{ steps.generate_variable.outputs.me }}
      - name: Show variables 2
        env:
          ME: ${{ steps.generate_variable.outputs.me }}
        run: |
          echo ${{ env.ME }}